---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.2
  - name: mwrock/Windows2012R2
    transport:
      name: winrm
      elevated: true

suites:
  - name: server
    excludes: mwrock/Windows2012R2
    run_list:
      - recipe[networker::hosts]
      - recipe[networker::server]
      - recipe[networker::nmc]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    driver:
      network:
        - ['private_network', {ip: '10.10.10.10'}]
  - name: client
    excludes: mwrock/Windows2012R2
    run_list:
      - recipe[networker::hosts]
      - recipe[networker::client]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    driver:
      network:
        - ['private_network', {ip: '10.10.10.20'}]
  - name: client
    excludes: centos-7.2
    run_list:
      - recipe[networker::hosts]
      - recipe[networker::client]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    driver:
      network:
        - ['private_network', {ip: '10.10.10.30'}]